# Build Icecast - test
make_dist:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  tags:
    - docker

  image: alpine:3.12

  stage: build
#devel-stephan48-publish-bin-package
  before_script:
  - apk update
  - cat /etc/os*
  - apk add musl-dev git make gcc automake autoconf libtool curl ca-certificates
  - apk add curl-dev libogg-dev libvorbis-dev libxslt-dev libxml2-dev  libc6-compat
  # gzip required because busybox gzip does not understand best / zip for make dist
  - apk add gzip zip tar
  # Required for tests
  #- apk add curl ffmpeg
  # Create user to run tests
  #- adduser -s /bin/sh -D -H icecast

  script: 
    - ./autogen.sh
    - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
    - 'curl -LO --header "JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/143/packages/generic/libigloo-bins/0.0.1-$CI_COMMIT_REF_NAME/libigloo-$CI_COMMIT_REF_NAME.tar.gz"'
    - tar -C / -xvzf libigloo-$CI_COMMIT_REF_NAME.tar.gz
    - ls -la /usr/local/lib
    - ./configure || cat config.log
    - make dist
    - ls -la
    - make install DESTDIR=`pwd`/_install_base/
    - ls -la 
    - ls -la _install_base/
    - cd _install_base/
    - tar -cvzf ../icecast-$CI_COMMIT_REF_NAME.tar.gz *
    - cd ..
    - ls -la
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file libigloo-$CI_COMMIT_REF_NAME.tar.gz "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/icecast-bins/0.0.1-$CI_COMMIT_REF_NAME/icecast-$CI_COMMIT_REF_NAME.tar.gz"'  
    # Tests
    #- su -c "./tests/admin-tests.sh" icecast

  artifacts:
    paths:
      - icecast-*.tar.gz
      - icecast-*.zip
    expire_in: 1 week

upload_dist:
  tags:
    - docker
    - linux

  only:
    - master
    - devel

  stage: deploy

  dependencies:
    - make_dist

  before_script:
    - ./ci/osc/prepare-osc-tools.sh

  script:
    - ./ci/osc/handle-osc-upload.sh

upload_dist_release:
  tags:
    - docker
    - linux

  only:
    - tags

  stage: deploy

  dependencies:
    - make_dist

  before_script:
    - ./ci/osc/prepare-osc-tools.sh

  script:
    - ./ci/osc/handle-osc-upload.sh release
